USE laurea_exam;

INSERT INTO students (full_name, email, seat_number) VALUES
('Anoj Khadka', 'khadkaanoj92@gmail.com', 'H1R1D1'),
('Archana Singh', 'singharchana2165@gmail.com', 'H1R1D2'),
('Chhiring Bal Tamang', 'tamangchhiringbal@gmail.com', 'H1R1D3'),
('Darpan Bhandari', 'darpanb25a@gmail.com', 'H1R1D4'),
('Farah Shakeel', 'Farahshakeel668@gmail.com', 'H1R1D5'),
('Mahesh Silwal', 'maheshsilwal52@gmail.com', 'H1R1D6'),
('Sadikshya Uprety', 'sadikshyauprety97@gmail.com', 'H1R1D7'),
('Saman Bhatt', 'samanbhatt987@gmail.com', 'H1R1D8'),
('Siddhant Bhattarai', 'bhattaraisiddhant105@gmail.com', 'H1R1D9'),
('Sushil Thapa Magar', 'sushilthapamagar42@gmail.com', 'H1R1D10'),
('Anita Paudel', 'anitapaudel0000@gmail.com', 'H1R2D1'),
('Ayusha Budha Magar', 'ayushabudhamagar761@gmail.com', 'H1R2D2'),
('Laxmi Bhandari', 'laxmibhandari8520@gmail.com', 'H1R2D3'),
('Neelam Gurung Bartaula', 'gurungneelam93@gmail.com', 'H1R2D4'),
('Salina Khatri', 'salinakhatri542@gmail.com', 'H1R2D5'),
('Sriju K C', 'srijukc0000@gmail.com', 'H1R2D6'),
('Aashish Pudasaini', 'pudasainiasis98@gmail.com', 'H1R2D7'),
('Aayush Lama Thing', 'aayushlama1256@gmail.com', 'H1R2D8'),
('Anisha Khadka', 'anishakhadka9888@gmail.com', 'H1R2D9'),
('Anyul Basnet', 'anyulbasnet0@gmail.com', 'H1R2D10'),
('Ayush Pandey', 'pandeyayush1d@gmail.com', 'H1R3D1'),
('Koushan B K', 'koushanbk13@gmail.com', 'H1R3D2'),
('Kripa Rai', 'kriparaibas11@gmail.com', 'H1R3D3'),
('Pankaj Prasain', 'pankajprasain643@gmail.com', 'H1R3D4'),
('Rama Paudel', 'ramapaudel2076@gmail.com', 'H1R3D5'),
('Sadikchhya Shrestha', 'sadikchhyashrestha33@gmail.com', 'H1R3D6'),
('Samriddhi Niraula', 'finlandeur2026@gmail.com', 'H1R3D7'),
('Sanju Sunar', 'sunarsanju431@gmail.com', 'H1R3D8'),
('Shobha Rani Rayamajhi', 'shobharanirayamajhi@gmail.com', 'H1R3D9'),
('Srijan Poudel', 'srijanp124@gmail.com', 'H1R3D10'),
('Subod Basnet', 'subod.basnet25@gmail.com', 'H1R4D1'),
('Sudip Budhathoki', 'budhathokisudip631@gmail.com', 'H1R4D2'),
('Sujata K C', 'sujatakc871@gmail.com', 'H1R4D3'),
('Sulav Singh', 'singhsulav03@gmail.com', 'H1R4D4'),
('Supratik Timalsina', 'timalsinasupratik5@gmail.com', 'H1R4D5'),
('Sushil Luhar', 'succl810@gmail.com', 'H1R4D6'),
('Swaibika Shrestha', 'helsinkitraqs@gmail.com', 'H1R4D7'),
('Zidan Basnet', 'helsinkizidan@gmail.com', 'H1R4D8')
ON DUPLICATE KEY UPDATE
  full_name = VALUES(full_name),
  seat_number = VALUES(seat_number);
