-- Run this against your Neon database to create tables and seed data

CREATE TABLE IF NOT EXISTS students (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    seat_number VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS verified_students (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    seat_number VARCHAR(50) NOT NULL,
    verify_count INT NOT NULL DEFAULT 1,
    last_verified_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Clear old data and replace with new student list
TRUNCATE TABLE verified_students;
TRUNCATE TABLE students;

INSERT INTO students (full_name, email, seat_number) VALUES
('Anisha Ojha', 'anishaojha202@gmail.com', 'H1R1D1'),
('Anita Paudel', 'anitapaudel0000@gmail.com', 'H1R1D2'),
('Archana Singh', 'singharchana2165@gmail.com', 'H1R1D3'),
('Ashutosh Khadka', 'khadkaashutosh2@gmail.com', 'H1R1D4'),
('Ayusha Budha Magar', 'ayushabudhamagar761@gmail.com', 'H1R1D5'),
('Christina Budha', 'christinabudha5@gmail.com', 'H1R1D6'),
('Deepika Manandhar', 'mdrdeepika500@gmail.com', 'H1R1D7'),
('Eva Nepal', 'evanepal25@gmail.com', 'H1R1D8'),
('Kanchan Dhami', 'kanchandhami2026@gmail.com', 'H1R1D9'),
('Neelam Gurung Bartaula', 'gurungneelam93@gmail.com', 'H1R1D10'),
('Pratima Chaudhary', '26pratimachaudhary@gmail.com', 'H1R2D1'),
('Pabita Kumari Thapa', 'mpabita003@gmail.com', 'H1R2D2'),
('Ritika Kumari Singh', 'ritikaofficial699@gmail.com', 'H1R2D3'),
('Sandesh Neupane', 'sandeshneupane9867@gmail.com', 'H1R2D4'),
('Shobha Rani Rayamajhi', 'rani.shobha09@gmail.com', 'H1R2D6'),
('Shuvam Dahal', 'shuvamdahal919@gmail.com', 'H1R2D7'),
('Sirjana Sen Parajuli', 'parajulisirjana38@gmail.com', 'H1R2D8'),
('Sriju K C', 'srijukc0000@gmail.com', 'H1R2D9'),
('Swostika Tamang', 's45756386@gmail.com', 'H1R2D10'),
('Tomi Kala Saru', 'tomikalasaru9@gmail.com', 'H1R3D1'),
('Aashika Ranabhat', 'aashikaranabhat277@gmail.com', 'H1R3D2'),
('Abhimanyu Paudel', 'abhimanyupaudel2026@gmail.com', 'H1R3D3'),
('Barun Jung Chepang', 'barunjungchepang@gmail.com', 'H1R3D4'),
('Chhiring Bal Tamang', 'tamangchhiringbal@gmail.com', 'H1R3D5'),
('Ganjesh Sing Thapa', 'ganjeshthapa1289@gmail.com', 'H1R3D6'),
('Hemal Rajbongshi', 'hemalrajbongshi753@gmail.com', 'H1R3D7'),
('Krish Pudasaini', 'krishpudasaini010@gmail.com', 'H1R3D8'),
('Kushma Gurung', 'gurungkushma03@gmail.com', 'H1R3D9'),
('Laxmi Bhandari', 'laxmibhandari8520@gmail.com', 'H1R3D10'),
('Rupak Thing', 'rupakthing361@gmail.com', 'H1R4D1'),
('Sabin Dahal', 'sabin.dahal1@hotmail.com', 'H1R4D2'),
('Salina Khatri', 'salinakhatri542@gmail.com', 'H1R4D3'),
('Saman Bhatt', 'samanbhatt987@gmail.com', 'H1R4D4'),
('Samyak Shakya', 'samy4kshakya@gmail.com', 'H1R4D5'),
('Shyam Mahato', 'shyammahato1850@gmail.com', 'H1R4D6'),
('Yunish Karki', 'yunish33022@gmail.com', 'H1R4D7'),
('Anisha Khadka', 'anishakhadka9888@gmail.com', 'H1R4D8'),
('Anita Shahi', 'anitashahifinland18@gmail.com', 'H1R4D9'),
('Arjun Bist', 'abist9691@gmail.com', 'H1R4D10'),
('Kalpana Bist', 'kalpanabist891@gmail.com', 'H1R5D1'),
('Kripa Rai', 'kriparaibas11@gmail.com', 'H1R5D2'),
('Lovely Magar', 'lovelydrm260@gmail.com', 'H1R5D3'),
('Prajwal Gautam', 'prajwal33022@gmail.com', 'H1R5D4'),
('Samriddhi Niraula', 'finlandeur2026@gmail.com', 'H1R5D5'),
('Sanju Sunar', 'sunarsanju431@gmail.com', 'H1R5D6'),
('Sonali Chhetri', 'chhetrisonali336@gmail.com', 'H1R5D7'),
('Sujata Dahal', 'sujatadhl95@gmail.com', 'H1R5D8'),
('Sujata K C', 'sujatakc871@gmail.com', 'H1R5D9'),
('Swaibika Shrestha', 'tokyotraqs@gmail.com', 'H1R5D10'),
('Aayush Thapa', 'aayushthapa5025@gmail.com', 'H2R1D1'),
('Abhishek Shahi', 'abhishahi026@gmail.com', 'H2R1D2'),
('Abhishek Gupta', 'email2guptaabhi981@gmail.com', 'H2R1D3'),
('Achut Neupane', 'achutneupane855@gmail.com', 'H2R1D4'),
('ambar shukla', 'shuklaamar779@gmail.com', 'H2R1D5'),
('ambar shukla', 'ambarshukla769@gmail.com', 'H2R1D6'),
('Anish Kumar Shah', 'anishkumarshah21@gmail.com', 'H2R1D7'),
('Anuja Regmi', 'regmianuja32@gmail.com', 'H2R1D8'),
('Anuja Luitel', 'anujaluitel2@gmail.com', 'H2R1D9'),
('Archana Chudal', 'chudalarchana147@gmail.com', 'H2R1D10'),
('Arun Khadka', 'khadkaarun2025@gmail.com', 'H2R2D1'),
('Ashim Adhikari', 'ashimadhikari830@gmail.com', 'H2R2D2'),
('Astha Thapa', 'aasthathapa1332@gmail.com', 'H2R2D3'),
('Atish kumar Chaudhary', 'atishkumarchaudharybas@gmail.com', 'H2R2D4'),
('Bina Rawal', 'rawalbina339@gmail.com', 'H2R2D5'),
('Bindu Sarki Nepali', 'nepalibindu02@gmail.com', 'H2R2D6'),
('Binu Ghalan', 'ghalanbinu290@gmail.com', 'H2R2D7'),
('Bipika Nepal', 'bipikanepal2001@gmail.com', 'H2R2D8'),
('Bishal Magar', 'bm983640@gmail.com', 'H2R2D9'),
('Bishnu Pandey', 'pbishnu5156@gmail.com', 'H2R2D10'),
('Chiranjivi Roka', 'chiranjiviroka3@gmail.com', 'H2R3D1'),
('David Chaudhary', 'chaudharydavid35@gmail.com', 'H2R3D2'),
('Dayna Shrestha', 'daynashresthabas@gmail.com', 'H2R3D3'),
('Deepak Chaudhary', 'audit.deep01@gmail.com', 'H2R3D4'),
('Deepesh Khadka', 'khadkadeepesh14@gmail.com', 'H2R3D5'),
('Deepesh Thapa', 'deepeshthapa2026@gmail.com', 'H2R3D6'),
('Dickhha Basnet', 'dickhhabasnet@gmail.com', 'H2R3D7'),
('Dipika Sharma Sapkota', 'dipikasapkota201@gmail.com', 'H2R3D8'),
('Durga Kumari Pokharel', 'durga.karki7070@gmail.com', 'H2R3D9'),
('Eljina Mote', 'eljinamote6@gmail.com', 'H2R3D10'),
('Ganesh Budha', 'kazisurya136@gmail.com', 'H2R4D1'),
('Ganesh Subedi', 'subediganesh851@gmail.com', 'H2R4D2'),
('Goma Thapa', 'goma63312@gmail.com', 'H2R4D3'),
('Hari Prasad Adhikari', 'adhikarihariprasad@gmail.com', 'H2R4D4'),
('Kamala Joshi', 'kamalafinland@gmail.com', 'H2R4D5'),
('Karisma Rana', 'ranakarisma567@gmail.com', 'H2R4D6'),
('Karsang Dolma Tamang', 'karsangdolmatamang7@gmail.com', 'H2R4D7'),
('KESHAB RIJAL', 'keshabrijal033@gmail.com', 'H2R4D8'),
('LILA CHAUDHARY', 'lilachaudhary2026@gmail.com', 'H2R4D9'),
('Lina Adhikari', 'linaadhikari20@gmail.com', 'H2R4D10'),
('Madhav Adhikari', 'madhav.adhikari@hotmail.com', 'H2R5D1'),
('Madhusudan Chudali', 'chudalimadhusudan85@gmail.com', 'H2R5D2'),
('Manisha Khadka', 'manishakhadka3030@gmail.com', 'H2R5D3'),
('Mira Pokhrel', 'mirapokhrel149@gmail.com', 'H2R5D4'),
('Muna Karki', 'muna.karki1@hotmail.com', 'H2R5D5'),
('Najrullah Ansari', 'najruansari@proton.me', 'H2R5D6'),
('Nasib Tharu', 'tharunasib2026@gmail.com', 'H2R5D7'),
('Nirmala Jaishi', 'nirmalajaishi234@gmail.com', 'H2R5D8'),
('Nita Dangol', 'nitadangol9@gmail.com', 'H2R5D9'),
('Nitya Raj Dhungana', 'nityadhungana67@gmail.com', 'H2R5D10'),
('Partiva Madai', 'partivamadai9@gmail.com', 'H2R6D1'),
('POOJA GARG AGRAWAL', 'pgargagrawal@gmail.com', 'H2R6D2'),
('Prashant Magar', 'magarprashant089@gmail.com', 'H2R6D3'),
('Pratima Kandel', 'pratimakandel147@gmail.com', 'H2R6D4'),
('Prinsha Limbu', 'limbuprinsha14@gmail.com', 'H2R6D5'),
('PUJAN PRADHAN', 'pujanpradhan885@gmail.com', 'H2R6D6'),
('Rajkumar Lama Ghising', 'rlamaghising@gmail.com', 'H2R6D7'),
('Rasmita Karki', 'karkirasmita34@gmail.com', 'H2R6D8'),
('Rita Gaire', 'ritagaire611@gmail.com', 'H2R6D9'),
('RUPA KUMARI THAPA', 'rupakumarit816@gmail.com', 'H2R6D10'),
('Sachin Khanal', 'sachinkhanal197@gmail.com', 'H2R7D1'),
('Sagar Pakhrin Tamang', 'sagarpakhrint@gmail.com', 'H2R7D2'),
('Sajjan Sigdel', 'sajjansigdel7@gmail.com', 'H2R7D3'),
('Samana Shrestha', 'samanashrestha52@gmail.com', 'H2R7D4'),
('Samjhana Paudel', 'samjhanapaudel37@gmail.com', 'H2R7D5'),
('Sanam Roka Magar', 'sanamrokamagarbas@gmail.com', 'H2R7D6'),
('Sandesh Pradhan', 'sandeshpradhan91@gmail.com', 'H2R7D7'),
('Sangam Parajuli', 'sangamparajuli111@gmail.com', 'H2R7D8'),
('Sansil Rai', 'sanshilrai30@gmail.com', 'H2R7D9'),
('SANTOSH LAMICHHANE', 'lamichhanesantosh061@gmail.com', 'H2R7D10'),
('Sapna Banjade', 'banjadesapna9@gmail.com', 'H2R8D1 & H1R2D5'),
('Sarada Gupta', 'guptasarada0@gmail.com', 'H2R8D2'),
('Sarala Sunuwar Rai', 'saralasunuwarrai00@gmail.com', 'H2R8D3'),
('SARMILA BOHAJU', 'sarmilabohaju031@gmail.com', 'H2R8D4'),
('Saujanaya Singh Thakuri', 'saujanaya06ld@gmail.com', 'H2R8D5'),
('Sharan Mahat', 'sharanmahat898@gmail.com', 'H2R8D6'),
('Sharmila Hamal', 'saruhh8848@gmail.com', 'H2R8D7'),
('Shashi Kala Rai', 'raishashikala008@gmail.com', 'H2R8D8'),
('Shojan Shrestha', 'shojanshrestha27@gmail.com', 'H2R8D9'),
('Shrestha Arjun Kumar', 'arjunkumarshrestha687@gmail.com', 'H2R8D10'),
('Shrijana Khatri', 'shrijanakhatribas@gmail.com', 'H2R9D1'),
('Shyam Kumar Giri', 'shyamgiri2027@gmail.com', 'H2R9D2'),
('Sirjana Gurung', 'sirzanag0464176@gmail.com', 'H2R9D3'),
('Srijana Maharjan', 'srijana.maharjan@hotmail.com', 'H2R9D4'),
('Sudip Acharya', 'sudipacharya169@gmail.com', 'H2R9D5'),
('Sugandha Lungayli', 'lungaylisugandha@gmail.com', 'H2R9D6'),
('Suman Dahal', 'suman1990dal@gmail.com', 'H2R9D7'),
('Suresh Raj Bhatta', 'bhattas330@gmail.com', 'H2R9D8'),
('Sushma Subedi', 'subedisushma188@gmail.com', 'H2R9D9'),
('Sushma Nepali', 'nepalisushma95@gmail.com', 'H2R9D10'),
('Sushma Dangoriya Tharu', 'sushma.0808b@gmail.com', 'H2R10D1'),
('Uma Dhakal Gautam', 'dhakaluma511@gmail.com', 'H2R10D2'),
('Yogita Pandey', 'yogitapandey591@gmail.com', 'H2R10D3'),
('Yubraj Karki', 'kyubraj554@gmail.com', 'H2R10D4')
ON CONFLICT (email) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  seat_number = EXCLUDED.seat_number;
